language: php

php:
  - nightly
  - "7.4"
  - "7.3"
  - "7.2"

env:
  - RUN_PHPUNIT=1 CSCHECK=0

matrix:
  include:
    - php: "7.2"
      env: RUN_PHPUNIT=0 CSCHECK=1

  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - if [ "$RUN_PHPUNIT" = "1" ]; then vendor/bin/phpunit -c phpunit.xml; fi;
  - if [ "$CSCHECK" = "1" ]; then vendor/bin/phpcs; fi;
